import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { Provider } from "./lib/utils/provider";
import { getServerSession } from "next-auth";
import Header from "./components/ui/Header";
import "./globals.css";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Manhattan",
  description: "Generated by Sohail Iqrar"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <Provider session={session}>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </Provider>
    </html>
  );
}
